name: Build and test

on: [push, pull_request]

jobs:
  win64:
    name: Build & Test Win64
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --release

  osx:
    name: Build & Test OS-X
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --release

  linux:
    name: Build & Test Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --release
